#!/usr/bin/env bash
 
rofi -show drun -modi run,drun -no-lazy-grab -scroll-method 0 \
-drun-match-fields all -drun-display-format "{name}" -no-drun-show-actions \
-terminal alacritty -theme "$HOME"/.config/rofi/themes/launcher.rasi
